export const data= {
        "name":"public",
        "isFolder":true,
        "items":[
            {
                "name":"index.html",
                "isFolder":false
            },
            {
                "name":"images",
                "isFolder":true,
                items:[
                    {
                        name:"image1.jpg",
                        isFolder:false,
                    },
                    {
                        name:"image2.jpg",
                        isFolder:false,
                    },
                    {
                        name:"image3.jpg",
                        isFolder:false,
                    },
                ]
            },
            {
                "name":"styles.css",
                "isFolder":false
            }
        ]
    }
